### ISSUE TITLE
A small question about lambda

### ISSUE THREAD

**Issue by v587su** [oval-group/dfw#2]
Hello, why do you use lambda here?Just be curious

![image](https://user-images.githubusercontent.com/28437985/54802684-52911500-4ca7-11e9-963d-b15924346462.png)

**Comment by lberrada** [comment]
This is so that when `args.dump_epoch` is true, the filename is generated again at each call, and therefore the index of the current epoch in the filename (given by `xp.Epoch.value`) is correctly updated

**Comment by v587su** [comment]
I get it. Thank you.
